### ISSUE TITLE
[RoadMap] v0.1.0 first release plan

### ISSUE THREAD

**Issue by laekov** [laekov/fastmoe#1]
## Functions

- [x] A model-injection-style easy-to-use user interface. 
- [x] Support both data parallel and model parallel, and a hybrid of the two, using a new customized DDP module.
- [x] Remove dependency to specific modified Megatron Repository.
- [x] Support to customized `nn.Module` as an expert.

## Document and infrastructure

- [x] Use PyTest instead of current shell script, and add more tests.
- [x] Installation and usage guide.
- [x]  launching using PyTorch's native distributed launcher
- [x] Explanation of functions and code structure
- [x] Add a license Apache v2.0 the last commit before releasing

## Performance

- [x] A well-organized benchmark
